name: EditorConfig Check

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install editorconfig-checker
        run: npm install -g editorconfig-checker

      - name: Run EditorConfig Checker
        run: editorconfig-checker
